[package]
name = "basic-example-script"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[dependencies]
basic-example = { path = "../token" }
alloy-primitives.workspace = true
alloy.workspace = true
tokio.workspace = true
