[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "link-arg=-zstack-size=8192",
    "-C",
    "target-cpu=mvp",
    "-C",
    "target-feature=+bulk-memory",
]

#TODO#q: remove -A warnings suppress flag
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup", "-A", "warnings"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]
