[package]
name = "pedersen-example"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[dependencies]
openzeppelin-crypto = { workspace = true, features = ["ruint"] }
alloy-primitives.workspace = true
stylus-sdk.workspace = true

[dev-dependencies]
alloy.workspace = true
e2e.workspace = true
tokio.workspace = true
eyre.workspace = true
alloy-primitives = { workspace = true, features = ["tiny-keccak"] }

[lib]
crate-type = ["lib", "cdylib"]

[features]
e2e = []
export-abi = ["stylus-sdk/export-abi"]
contract-client-gen = []

[[bin]]
name = "pedersen-example"
path = "src/main.rs"
